# ---------- build stage ----------
FROM golang:1.25-alpine AS build

WORKDIR /app

# Copy go mod files first (better caching)
COPY go.mod go.sum ./
RUN go mod download

# Copy entire repo (needed because module root is here)
COPY . .

# Build the gRPC server binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o emp-api .

# ---------- runtime stage ----------
FROM gcr.io/distroless/base-debian12

WORKDIR /app

COPY --from=build /app/emp-api /app/emp-api

EXPOSE 50051
USER nonroot:nonroot

ENTRYPOINT ["/app/emp-api"]

