{
 "title": "go-api dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "caller",
    "query": {
     "query": "label_values(http_request_duration_seconds_new_bucket, caller)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current P95",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(http_request_duration_seconds_new_bucket{caller=~\"$caller\"}[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Current RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    http_request_duration_seconds_new_count{\n      caller=~\"$caller\"\n    }[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(\n      http_request_duration_seconds_new_bucket{\n        caller=~\"$caller\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(http_request_duration_seconds_new_bucket{caller=~\"$caller\"}[5m])\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(http_request_duration_seconds_new_bucket{caller=~\"$caller\"}[5m])\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(http_request_duration_seconds_new_bucket{caller=~\"$caller\"}[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le)(\n  rate(\n    http_request_duration_seconds_new_bucket{\n      caller=~\"$caller\"\n    }[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    http_request_duration_seconds_new_count{\n      caller=~\"$caller\"\n    }[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}