{
 "title": "gp-api caller analysis",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "caller distrubution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (caller)(\n  increase(http_request_duration_seconds_new_count[1h])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Percentiles per caller",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, caller)(\n    rate(http_request_duration_seconds_new_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request per caller",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (caller)(\n  rate(http_request_duration_seconds_new_count[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}