apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-monitor
  labels:
    release: prometheus   # MUST match your Prometheus Helm release name
spec:
  selector:
    matchLabels:
      app: otel-collector
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 5s
