{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
        - name: employee-service
          image: {{ .Values.backend.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # 1. Fetch DB Username from ESO Secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret.name | quote }}
                  key: {{ .Values.database.existingSecret.userKey | quote }}
            
            # 2. Fetch DB Password from ESO Secret
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret.name | quote }}
                  key: {{ .Values.database.existingSecret.passKey | quote }}

            # 3. Fetch static DB configs from values.yaml
            - name: DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: DB_NAME
              value: {{ .Values.database.name | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    app: employee-service
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  type: {{ .Values.backend.service.type }}
{{- end }}
